version: 2.1
orbs:
  android: circleci/android@1.0.3
jobs:
  build:
    executor:
      name: android/android-machine
    steps:
      - checkout
      - run:
          name: Run lint
          command: ./gradlew lint
      - store_artifacts:
          path: app/build/reports
          destination: reports
      - run:
          name: Assemble release build
          command: ./gradlew assembleRelease
    
workflows:
  sample:
      jobs:
        - build
